// js/store/state.js

export const state = {
    works: {}, 
    adminPicks: {}, 
    tags: {}, 
    tagNameToDataMap: new Map(), 
    categories: {},
    sortedWorkIds: { new: [], ranking: [], favorites: [] },
    sortedAdminIds: { manga: [], game: [] },
    currentPage: { new: 1, ranking: 1, admin_manga: 1, admin_game: 1, favorites: 1 },
    pageSize: { admin: 10, user: 40, favorites: 40 },
    sectionsCollapsed: { admin: false, user: false },
    clientId: null, 
    hideBadlyRated: false, 
    mosaicActive: false,
    highlightTagIds: new Set(), 
    hideTagIds: new Set(), 
    currentTagEditMode: 'highlight',
    currentUser: null, 
    favorites: new Set(), 
    myLists: {}, 
    myListItems: {}, 
    activeListId: null, 
    currentView: 'main',
    isInitialDataLoaded: { works: false, adminPicks: false },
    isGridHeightFixedForMobile: true,
    autoScrollOnPageChange: true,
};